"""
MintPy configuration template generator.

Generates a smallbaselineApp.cfg (or mintpy_config.txt) file that is
ready to use with: smallbaselineApp.py mintpy_config.txt
"""

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

MINTPY_CONFIG_TEMPLATE = """\
##------ dolphin2mintpy auto-generated configuration for MintPy ------##
## Generated by dolphin2mintpy v{version}
## Run with: smallbaselineApp.py {config_name}

########## Load Data ##########
mintpy.load.processor      = hyp3
mintpy.load.autoPath       = no

## Unwrapped interferograms
mintpy.load.unwFile        = {unw_pattern}
## Coherence
mintpy.load.corFile        = {cor_pattern}
## Connected components (optional)
mintpy.load.connCompFile   = {conncomp_pattern}

## Geometry files (optional, but recommended)
mintpy.load.demFile        = {dem_pattern}
mintpy.load.incAngleFile   = {inc_angle_pattern}
mintpy.load.azAngleFile    = {az_angle_pattern}
mintpy.load.waterMaskFile  = {water_mask_pattern}

########## Reference Point ##########
## auto: use the pixel with highest coherence
## manual: specify lat/lon or y/x
mintpy.reference.lalo      = auto
## mintpy.reference.yx     = auto

########## Network Inversion ##########
mintpy.networkInversion.weightFunc = no

########## Tropospheric Delay Correction ##########
## Options: no / pyaps / height_correlation / gacos
mintpy.troposphericDelay.method = no

########## Topographic Residual (DEM Error) ##########
mintpy.topographicResidual = {topo_residual}

########## Velocity Estimation ##########
mintpy.deramp              = no

########## Output ##########
mintpy.save.hdfEos5        = no
mintpy.save.kmz            = yes
"""


def generate_mintpy_config(
    work_dir,
    unw_dir,
    cor_dir=None,
    conncomp_dir=None,
    dem_file=None,
    inc_angle_file=None,
    az_angle_file=None,
    water_mask_file=None,
    config_name="mintpy_config.txt",
    custom_options=None,
):
    """Generate a MintPy-compatible configuration file.

    Creates a smallbaselineApp.cfg-style file with all load_data paths
    pre-configured to point at Dolphin outputs with .rsc sidecars.

    Parameters
    ----------
    work_dir : str or Path
        MintPy working directory (where config file will be written).
    unw_dir : str or Path
        Directory containing unwrapped phase GeoTIFFs.
    cor_dir : str or Path, optional
        Directory containing coherence GeoTIFFs. Defaults to unw_dir.
    conncomp_dir : str or Path, optional
        Directory containing connected component files. Defaults to unw_dir.
    dem_file : str or Path, optional
        Path or glob pattern to DEM file.
    inc_angle_file : str or Path, optional
        Path or glob pattern to incidence angle file.
    az_angle_file : str or Path, optional
        Path or glob pattern to azimuth angle file.
    water_mask_file : str or Path, optional
        Path or glob pattern to water mask file.
    config_name : str
        Output filename for the configuration.
    custom_options : dict, optional
        Additional MintPy options to append (key=value pairs).

    Returns
    -------
    Path
        Absolute path to the generated config file.
    """
    from dolphin2mintpy import __version__

    work_dir = Path(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)

    unw_dir = Path(unw_dir)
    cor_dir = Path(cor_dir) if cor_dir else unw_dir
    conncomp_dir = Path(conncomp_dir) if conncomp_dir else unw_dir

    # Build glob patterns for MintPy load_data
    unw_pattern = _build_pattern(unw_dir, "*.unw.tif")
    cor_pattern = _build_pattern(cor_dir, "*.cor.tif", fallback="*.int.cor.tif")
    conncomp_pattern = _build_pattern(conncomp_dir, "*.conncomp.tif")

    # Geometry patterns
    dem_pattern = str(dem_file) if dem_file else "auto"
    inc_pattern = str(inc_angle_file) if inc_angle_file else "auto"
    az_pattern = str(az_angle_file) if az_angle_file else "auto"
    water_pattern = str(water_mask_file) if water_mask_file else "auto"

    # Determine if topographic residual should be enabled
    topo_residual = "yes" if dem_file else "no"

    content = MINTPY_CONFIG_TEMPLATE.format(
        version=__version__,
        config_name=config_name,
        unw_pattern=unw_pattern,
        cor_pattern=cor_pattern,
        conncomp_pattern=conncomp_pattern,
        dem_pattern=dem_pattern,
        inc_angle_pattern=inc_pattern,
        az_angle_pattern=az_pattern,
        water_mask_pattern=water_pattern,
        topo_residual=topo_residual,
    )

    # Append custom options
    if custom_options:
        content += "\n########## Custom Options ##########\n"
        for key, value in custom_options.items():
            content += f"{key:<35s} = {value}\n"

    config_path = work_dir / config_name
    with open(config_path, "w") as f:
        f.write(content)

    logger.info("Generated MintPy config: %s", config_path)
    return config_path


def _build_pattern(directory, primary_pattern, fallback=None):
    """Build a glob pattern string for MintPy load configuration.

    Checks if files matching the primary pattern exist; if not,
    tries the fallback pattern.

    Parameters
    ----------
    directory : Path
        Directory containing the files.
    primary_pattern : str
        Primary glob pattern to try.
    fallback : str, optional
        Fallback glob pattern if primary yields no matches.

    Returns
    -------
    str
        Full glob pattern string (directory/pattern).
    """
    full_pattern = str(directory / primary_pattern)

    if fallback:
        import glob as g
        if not g.glob(full_pattern):
            alt_pattern = str(directory / fallback)
            if g.glob(alt_pattern):
                return alt_pattern

    return full_pattern
